# Generated by Django 4.2.3 on 2023-07-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedoresApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
