# Generated by Django 4.2.3 on 2023-08-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedoresApp', '0002_alter_categorias_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='unidadStock',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombrecorto',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
