# Generated by Django 4.2.3 on 2023-08-04 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedoresApp', '0003_unidadmedida_unidadstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='unidadMedida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenedoresApp.unidadmedida'),
        ),
    ]
