# Generated by Django 4.2.3 on 2023-08-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaApp', '0004_alter_empresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteconfig',
            name='numerocont',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comprobanteconfig',
            name='serie',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
