# Generated by Django 4.2.3 on 2023-08-01 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresaApp', '0005_alter_comprobanteconfig_numerocont_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteconfig',
            name='tipocomprobante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresaApp.tipocomprobantes', unique=True),
        ),
    ]
