# Generated by Django 4.2.3 on 2023-09-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaApp', '0007_alter_comprobanteconfig_tipocomprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='correo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
