# Generated by Django 4.2.3 on 2023-10-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaApp', '0008_empresa_correo_empresa_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_porcentaje', models.IntegerField(default='0', max_length=2)),
            ],
        ),
    ]
