# Generated by Django 4.2.3 on 2023-10-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaApp', '0009_impuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='valor_porcentaje',
            field=models.IntegerField(default='0'),
        ),
    ]
