# Generated by Django 4.2.3 on 2023-10-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaApp', '0010_alter_impuesto_valor_porcentaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monedas',
            old_name='nombrecorto',
            new_name='simbolo',
        ),
        migrations.AddField(
            model_name='monedas',
            name='codigo',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
