# Generated by Django 4.2.3 on 2023-10-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaApp', '0013_empresa_nombre_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ubigeo',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
