# Generated by Django 4.2.3 on 2023-10-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaApp', '0014_empresa_ubigeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='departamento',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='empresa',
            name='distrito',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='empresa',
            name='provincia',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='empresa',
            name='urbanizacion',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
