# Generated by Django 4.2.3 on 2023-10-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaApp', '0015_empresa_departamento_empresa_distrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
