# Generated by Django 4.2.3 on 2023-10-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresaApp', '0016_empresa_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='clave_sunat',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario_sunat',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
