# Generated by Django 4.2.3 on 2023-08-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresaApp', '0007_alter_comprobanteconfig_tipocomprobante'),
        ('mantenedoresApp', '0002_alter_categorias_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('numeroComprob', models.CharField(max_length=10)),
                ('compraTotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedoresApp.proveedores')),
                ('idTipoComprob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresaApp.tipocomprobantes')),
            ],
        ),
    ]
