# Generated by Django 4.2.3 on 2023-08-02 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedoresApp', '0002_alter_categorias_nombre'),
        ('inventarioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.compras')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedoresApp.productos')),
                ('idUniMedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedoresApp.unidadmedida')),
            ],
        ),
    ]
