# Generated by Django 4.2.3 on 2023-08-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedoresApp', '0003_unidadmedida_unidadstock_and_more'),
        ('inventarioApp', '0002_detallecompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('uniMedida', models.CharField(max_length=20)),
                ('precioUnidad', models.IntegerField()),
                ('precioDocena', models.IntegerField()),
                ('precioPaquete', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('idProducto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mantenedoresApp.productos')),
            ],
        ),
    ]
