# Generated by Django 4.2.3 on 2023-08-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0003_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='precioDocena',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='precioPaquete',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='precioUnidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='stock',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
