# Generated by Django 4.2.3 on 2023-08-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0004_alter_almacen_preciodocena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='uniMedida',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
