# Generated by Django 4.2.3 on 2023-08-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0005_alter_almacen_unimedida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacen',
            old_name='stock',
            new_name='cantidad',
        ),
        migrations.AddField(
            model_name='almacen',
            name='total',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
