# Generated by Django 4.2.3 on 2023-08-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0006_rename_stock_almacen_cantidad_almacen_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='idUniMedida',
        ),
    ]
