# Generated by Django 4.2.3 on 2023-08-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0007_remove_detallecompra_idunimedida'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='precioCompra',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
