# Generated by Django 4.2.3 on 2023-08-19 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedoresApp', '0004_productos_unidadmedida'),
        ('inventarioApp', '0008_almacen_preciocompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenPrecioUM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('idAlmacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.almacen')),
                ('idUnidadMed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mantenedoresApp.unidadmedida')),
            ],
        ),
    ]
