# Generated by Django 4.2.3 on 2023-08-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedoresApp', '0004_productos_unidadmedida'),
        ('inventarioApp', '0010_remove_almacen_preciodocena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenprecioum',
            name='idUnidadMed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedoresApp.unidadmedida'),
        ),
    ]
