# Generated by Django 4.2.3 on 2023-08-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0012_alter_compras_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
