# Generated by Django 4.2.3 on 2023-08-11 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenedoresApp', '0004_productos_unidadmedida'),
        ('empresaApp', '0007_alter_comprobanteconfig_tipocomprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.TextField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('idComprob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresaApp.tipocomprobantes')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('numComprobante', models.CharField(max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idPedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventaApp.pedidos')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipComprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresaApp.tipocomprobantes')),
            ],
        ),
        migrations.CreateModel(
            name='PedidosDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedoresApp.productos')),
            ],
        ),
    ]
