# Generated by Django 4.2.3 on 2023-08-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='metodoPago',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
