# Generated by Django 4.2.3 on 2023-08-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0002_pedidos_numero_pedidos_total_ventas_metodopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
