# Generated by Django 4.2.3 on 2023-08-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0013_alter_compras_fecha'),
        ('mantenedoresApp', '0004_productos_unidadmedida'),
        ('ventaApp', '0003_alter_pedidos_fecha_alter_pedidos_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidosdetalle',
            old_name='descripcion',
            new_name='comentario',
        ),
        migrations.RemoveField(
            model_name='pedidosdetalle',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='pedidosdetalle',
            name='idAlmacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.almacen'),
        ),
        migrations.AddField(
            model_name='pedidosdetalle',
            name='idPedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventaApp.pedidos'),
        ),
        migrations.AddField(
            model_name='pedidosdetalle',
            name='idUmVenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenedoresApp.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
