# Generated by Django 4.2.3 on 2023-08-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0004_rename_descripcion_pedidosdetalle_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
