# Generated by Django 4.2.3 on 2023-08-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0005_alter_pedidos_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
