# Generated by Django 4.2.3 on 2023-08-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0006_alter_pedidos_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosdetalle',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='pedidosdetalle',
            name='idUmVenta',
        ),
        migrations.AddField(
            model_name='pedidosdetalle',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidosdetalle',
            name='producto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedidosdetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidosdetalle',
            name='umVenta',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
