# Generated by Django 4.2.3 on 2023-08-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0007_remove_pedidosdetalle_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosdetalle',
            name='proporcion',
            field=models.IntegerField(null=True),
        ),
    ]
