# Generated by Django 4.2.3 on 2023-09-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0008_pedidosdetalle_proporcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='idPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventaApp.pedidos'),
        ),
    ]
