# Generated by Django 4.2.3 on 2023-09-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0009_alter_ventas_idpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='serie',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
