# Generated by Django 4.2.3 on 2023-10-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0010_ventas_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='igv_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
