# Generated by Django 4.2.3 on 2023-10-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0011_pedidos_igv_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='total',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='pedidosdetalle',
            old_name='subtotal',
            new_name='importe',
        ),
    ]
