# Generated by Django 4.2.3 on 2023-10-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresaApp', '0011_rename_nombrecorto_monedas_simbolo_monedas_codigo'),
        ('ventaApp', '0012_rename_total_pedidos_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='idMoneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresaApp.monedas'),
        ),
    ]
