# Generated by Django 4.2.3 on 2023-10-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0013_pedidos_idmoneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='cliente_doc',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
