# Generated by Django 4.2.3 on 2023-10-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaApp', '0014_pedidos_cliente_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='cliente_dir',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
